=== spacebelGIS/daobs/web/src/main/webapp/WEB-INF/xsd/daobsIndicatorConfig.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" targetNamespace="http://daobs.org" xmlns:daobs="http://daobs.org">
  <xs:import namespace="http://www.w3.org/XML/1998/namespace" schemaLocation="xml.xsd"/>
  <xs:element name="reporting">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:variables"/>
        <xs:element ref="daobs:indicators"/>
      </xs:sequence>
      <xs:attribute name="computationTime" type="xs:int"/>
    </xs:complexType>
    <xs:key name="indicator-id-key">
      <xs:selector xpath="daobs:variables/daobs:variable|daobs:indicators/daobs:indicator"/>
      <xs:field xpath="@id"/>
    </xs:key>
  </xs:element>
  <xs:element name="variables">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="daobs:variable"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="indicators">
    <xs:complexType mixed="true">
      <xs:sequence>
        <xs:element minOccurs="0" maxOccurs="unbounded" ref="daobs:indicator"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="variable">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:name"/>
        <xs:element ref="daobs:query"/>
        <xs:element ref="daobs:format" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:value" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:status" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:comment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="indicator">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="daobs:name"/>
        <xs:element ref="daobs:expression"/>
        <xs:element ref="daobs:parameters"/>
        <xs:element ref="daobs:format" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:value" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:status" minOccurs="0" maxOccurs="1"/>
        <xs:element ref="daobs:comment" minOccurs="0" maxOccurs="1"/>
      </xs:sequence>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="name">
    <xs:complexType mixed="true">
      <xs:attribute ref="xml:lang" use="optional"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="value" type="xs:string"/>
  <xs:element name="format" type="xs:string"/>
  <xs:element name="query" type="xs:string"/>
  <xs:element name="expression" type="xs:string"/>
  <xs:element name="comment" type="xs:string"/>
  <xs:element name="status" type="xs:string"/>
  <xs:element name="parameters">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="daobs:parameter"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="parameter">
    <xs:complexType>
      <xs:attribute name="id" use="required" type="xs:NCName"/>
      <xs:attribute name="status" use="optional" type="xs:string"/>
      <xs:attribute name="value" use="optional" type="xs:string"/>
    </xs:complexType>
    <!--<xs:keyref refer="daobs:indicator-id-key" name="indicator-id-fkey">
      <xs:selector xpath="."></xs:selector>
      <xs:field xpath="@id"></xs:field>
    </xs:keyref>-->
  </xs:element>
</xs:schema>

=== spacebelGIS/daobs/web/src/main/webapp/WEB-INF/reporting/config-inspire.xml
<daobs:reporting xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                 xsi:schemaLocation="http://daobs.org ../xsd/daobsIndicatorConfig.xsd"
                 xmlns:daobs="http://daobs.org"
                 id="inspire">
  <daobs:identification>
    <daobs:title xml:lang="en">Monitoring Indicators</daobs:title>
    <daobs:author>Monitoring and Reporting Drafting Team</daobs:author>
    <daobs:url>http://inspire.ec.europa.eu/index.cfm/pageid/5022</daobs:url>
  </daobs:identification>

  <daobs:variables>

    <!-- Indicator MDi1 (Existence of metadata) -->

    <!-- DSv are estimates based on metadata. See MDvXX.
    The reported value may be more than this. -->
    <daobs:variable id="DSv_Num1">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:i</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be underestimated
        if the number of spatial data set does not have metadata or if error occurred
        during harvesting.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv_Num2">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:ii</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be underestimated
        if the number of spatial data set does not have metadata or if error occurred
        during harvesting.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv_Num3">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:iii</daobs:query>
      <daobs:comment>The value is based on the harvested records. It may be underestimated
        if the number of spatial data set does not have metadata or if error occurred
        during harvesting.</daobs:comment>
    </daobs:variable>


    <daobs:variable id="SDSv_Num">
      <daobs:name xml:lang="en">Number of spatial data services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment>Only services having an INSPIRE annex are took into account. We may harvest records related to no annex.</daobs:comment>
    </daobs:variable>


    <daobs:variable id="NSv_NumDiscServ">
      <daobs:name xml:lang="en">Number of discovery services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:discovery</daobs:query>
    </daobs:variable>

    <daobs:variable id="NSv_NumViewServ">
      <daobs:name xml:lang="en">Number of view services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:view</daobs:query>
    </daobs:variable>

    <daobs:variable id="NSv_NumDownlServ">
      <daobs:name xml:lang="en">Number of download services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:download</daobs:query>
    </daobs:variable>

    <daobs:variable id="NSv_NumInvkServ">
      <daobs:name xml:lang="en">Number of invoke services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:invoke</daobs:query>
    </daobs:variable>

    <daobs:variable id="NSv_NumTransfServ">
      <daobs:name xml:lang="en">Number of transformation services</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii) +inspireServiceType:transformation</daobs:query>
    </daobs:variable>



    <daobs:variable id="MDv11">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I that have metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:i</daobs:query>
    </daobs:variable>

    <daobs:variable id="MDv12">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II that have metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:ii</daobs:query>
    </daobs:variable>

    <daobs:variable id="MDv13">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III that have metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireAnnex:iii</daobs:query>
    </daobs:variable>



    <daobs:variable id="MDv14">
      <daobs:name xml:lang="en">Number of spatial data services that have metadata</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
    </daobs:variable>


    <!-- Indicator MDi2 (Conformity of metadata) -->
    <daobs:variable id="MDv21">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex I that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:i</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv22">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex II that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:ii</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv23">
      <daobs:name xml:lang="en">Number of spatial data sets for Annex III that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:iii</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="MDv24">
      <daobs:name xml:lang="en">Number of spatial data services that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:service) +inspireConformMetadata:true +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>


    <!-- INSPIRE DSi1 (Geographical coverage of spatial data sets) -->

    <!-- INSPIRE DSi2 (Conformity of spatial data sets) -->
    <daobs:variable id="DSv21">
      <daobs:name xml:lang="en">Number of conformant spatial data sets for Annex I that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:i +inspireConformResource:true</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv22">
      <daobs:name xml:lang="en">Number of conformant spatial data sets for Annex II that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:ii +inspireConformResource:true</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>

    <daobs:variable id="DSv23">
      <daobs:name xml:lang="en">Number of conformant spatial data sets for Annex III that have conformant metadata</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +inspireConformMetadata:true +inspireAnnex:iii +inspireConformResource:true</daobs:query>
      <daobs:comment>TODO: Metadata are not validated yet. So this value should be 0.</daobs:comment>
    </daobs:variable>


    <!-- INSPIRE NSi1 (Accessibility of metadata through discovery services) -->
    <daobs:variable id="NSv11">
      <daobs:name xml:lang="en">Number of spatial data sets with metadata for which a discovery service exists</daobs:name>
      <daobs:query>+(resourceType:dataset resourceType:series) +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment>All records used to build the report are harvested, so all records are available through discovery service (ie. equivalent to DSv_Num).</daobs:comment>
    </daobs:variable>
    <daobs:variable id="NSv12">
      <daobs:name xml:lang="en">Number of spatial data services with metadata for which a discovery service exists</daobs:name>
      <daobs:query>+resourceType:service +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment>All records used to build the report are harvested, so all records are available through discovery service (ie. equivalent to SDSv_Num).</daobs:comment>
    </daobs:variable>


    <!-- INSPIRE NSi2 (Accessibility of data sets through view or download services) -->
    <daobs:variable id="NSv21">
      <daobs:name xml:lang="en">Number of spatial data sets for which a view service exists</daobs:name>
      <daobs:query>{!child of=documentType:metadata} +documentType:metadata +resourceType:service +serviceType:view +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment></daobs:comment>
    </daobs:variable>
    <daobs:variable id="NSv22">
      <daobs:name xml:lang="en">Number of spatial data sets for which a download service exists</daobs:name>
      <daobs:query>{!child of=documentType:metadata} +documentType:metadata +resourceType:service +serviceType:download +(inspireAnnex:i inspireAnnex:ii inspireAnnex:iii)</daobs:query>
      <daobs:comment></daobs:comment>
    </daobs:variable>
    <!-- TODO view and download NSv23 -->



    <daobs:variable id="NSv41">
      <daobs:name xml:lang="en">Number of conformant discovery network services</daobs:name>
